package ru.otus.otuskotlin.resume.backend.common.exceptions

object NoneException : Throwable()